/**
 * CHARTER.md, generated from charter/constitution.yaml.
 *
 * Article 156, code as source of truth. Hand-written architecture documentation drifts from
 * the thing it describes within about two commits, and the drift is invisible because both
 * files read plausibly. Generating the prose from the enforced configuration means the
 * document is wrong only if the organization is wrong -- and a test asserts the committed
 * copy matches, so a stale CHARTER.md fails CI rather than misleading a reader.
 */

const wrap = (s) => String(s || '').replace(/\s+/g, ' ').trim();

export const charterDoc = (org) => {
  const c = org.constitution;
  const L = [];
  const seatName = (id) => org.roster.board.find((b) => b.id === id)?.seat ?? id;

  L.push(`# ${c.meta.name} — Charter`);
  L.push('');
  L.push(`**${c.meta.expands_to}** · v${c.meta.version}`);
  L.push('');
  L.push(`> ${wrap(c.meta.premise)}`);
  L.push('');
  L.push(`North star: **${c.meta.north_star}**`);
  L.push('');
  L.push('<!-- Generated by `forge charter --apply` from charter/constitution.yaml. Edit the YAML. -->');
  L.push('');
  L.push('---');
  L.push('');
  L.push('## No chief executive');
  L.push('');
  L.push(wrap(c.board.chair_authority));
  L.push('');
  L.push('| Seat | Divisions owned | Answers for |');
  L.push('|---|---|---|');
  for (const b of org.roster.board) {
    const owns = c.board.portfolios.find((p) => p.seat === b.id).owns
      .map((d) => c.divisions.find((x) => x.id === d).name)
      .join(', ');
    L.push(`| **${b.seat}** | ${owns} | ${wrap(b.owns)} |`);
  }
  L.push('');
  L.push('### How the board resolves a disagreement');
  L.push('');
  for (const r of c.board.resolution) L.push(`1. ${wrap(r)}`);
  L.push('');
  L.push('### Channels that may bypass a seat');
  L.push('');
  L.push('Everything not listed here routes seat → manager → specialist. An undeclared channel is an untraceable one.');
  L.push('');
  for (const ch of c.board.direct_channels) {
    const names = ch.between.map((d) => c.divisions.find((x) => x.id === d).name).join(' ↔ ');
    L.push(`- **${names}** — ${wrap(ch.why)}`);
  }
  L.push('');
  L.push('---');
  L.push('');
  L.push('## The rules');
  L.push('');
  L.push('Every rule names the check that enforces it. A rule with no enforcement is a comment with a serial number, so `forge doctor` refuses to run if a rule points at a check that does not exist.');
  L.push('');
  for (const r of c.rules) {
    L.push(`### ${r.id} — ${r.title}`);
    L.push('');
    L.push(wrap(r.statement));
    L.push('');
    L.push(`\`enforced by: ${r.check}\``);
    L.push('');
  }
  L.push('---');
  L.push('');
  L.push('## The twelve divisions');
  L.push('');
  L.push('Immutable. The autonomous system may improve, replace and retire agents. It may not add, remove, merge or rename a division — only the Principal can, by editing the constitution by hand.');
  L.push('');
  L.push('| Division | Owning seat | Mission | Authority |');
  L.push('|---|---|---|---|');
  for (const d of c.divisions) {
    L.push(`| **${d.name}** (${d.code}) | ${seatName(org.seatOf.get(d.id))} | ${wrap(d.mission)} | ${wrap(d.authority)}${d.may_halt ? ' **May halt a campaign.**' : ''} |`);
  }
  L.push('');
  L.push('---');
  L.push('');
  L.push('## The principles');
  L.push('');
  L.push('Phrased as behaviour rather than as virtue. "Brutal honesty" is a mood; "a failure is reported as a failure" is a check.');
  L.push('');
  for (const p of c.board.principles) L.push(`- **${p.name}** — ${wrap(p.behaviour)}`);
  L.push('');
  L.push('---');
  L.push('');
  L.push('## The gates');
  L.push('');
  L.push('The loudest thing the organization does. Deliberately few — a gate that fires on everything is a gate nobody reads.');
  L.push('');
  for (const g of c.gates) {
    L.push(`### ${g.title}`);
    L.push('');
    L.push(`${wrap(g.why)}`);
    L.push('');
    L.push(`Fires on: ${g.matches.map((m) => `\`${m}\``).join(', ')}`);
    L.push('');
  }
  L.push('---');
  L.push('');
  L.push('## Escalation');
  L.push('');
  L.push('Each rung is tried before the next.');
  L.push('');
  c.escalation_ladder.forEach((r, i) => L.push(`${i + 1}. ${r}`));
  L.push('');
  L.push('Straight to the Principal, skipping the ladder:');
  L.push('');
  for (const e of c.escalate_immediately) L.push(`- ${e}`);
  L.push('');
  L.push('---');
  L.push('');
  L.push('## The handoff protocol');
  L.push('');
  L.push(`Required in every handoff: ${c.protocol.required.map((f) => `\`${f}\``).join(', ')}.`);
  L.push('');
  L.push(`Stated when they apply, and written as \`none\` when they do not: ${c.protocol.when_applicable.map((f) => `\`${f}\``).join(', ')}.`);
  L.push('');
  for (const r of c.protocol.rules) L.push(`- ${wrap(r)}`);
  L.push('');
  L.push(`**Failure is never bare.** Every failure carries a class: ${c.failure_classes.map((f) => `\`${f}\``).join(', ')}.`);
  L.push('');
  L.push('---');
  L.push('');
  L.push('## Circuit breakers');
  L.push('');
  L.push('Exceed → STOP → REPORT → ESCALATE. Never exceed → continue quietly.');
  L.push('');
  L.push('| Limit | Value |');
  L.push('|---|---|');
  for (const [k, v] of Object.entries(c.circuit_breakers)) L.push(`| ${k.replace(/_/g, ' ')} | ${v} |`);
  L.push('');
  L.push('---');
  L.push('');
  L.push('## Model tiers');
  L.push('');
  L.push('Capability classes, not vendors. The runtime binds them.');
  L.push('');
  for (const [k, v] of Object.entries(c.board.tier_policy)) {
    if (k === 'rules') continue;
    L.push(`- **${k}** — ${wrap(v)}`);
  }
  L.push('');
  for (const r of c.board.tier_policy.rules) L.push(`- ${wrap(r)}`);
  L.push('');
  return `${L.join('\n')}\n`;
};
