/**
 * One generated reference for the whole system.
 *
 * THE PROBLEM IT SOLVES
 *
 * Everything about how this organization works is already written down, across eight files
 * and sixty-eight generated agent prompts. A new reader — or future-you, six months on — has
 * to hunt. `explain --all` composes the lot into one document that can be read start to
 * finish.
 *
 * WHY IT CANNOT GO STALE
 *
 * Every section is rendered from the same source doctor already checks: the constitution for
 * rules, the roster for agents, routing.yaml cross-referenced against roster capabilities,
 * contracts.yaml for the inheritance, the CLI's own HELP string for the command surface, and
 * learn.mjs's FORBIDDEN/CAP constants read out of the code rather than described. A hand-
 * written architecture document drifts the moment someone edits YAML and forgets the prose.
 * This one cannot: regenerate it and any drift is a diff.
 *
 * The learning-limits section is the sharpest example. It prints the actual constants from
 * learn.mjs, so a doc claiming "at most 5 proposals" while the code says 8 is impossible.
 */

import fs from 'node:fs';
import path from 'node:path';
import { ROOT, paths, resolveContract } from './core.mjs';

const H = (n, t) => `${'#'.repeat(n)} ${t}`;

/** Pull the exported constants out of learn.mjs by reading the source, so prose cannot drift from code. */
const learningLimits = () => {
  const src = fs.readFileSync(path.join(ROOT, 'scripts', 'learn.mjs'), 'utf8');
  const cap = src.match(/export const CAP\s*=\s*\{([^}]*)\}/);
  const forbidden = src.match(/const FORBIDDEN\s*=\s*\[([^\]]*)\]/);
  return {
    cap: cap ? cap[1].trim() : '(not found — learn.mjs no longer exports CAP)',
    forbidden: forbidden
      ? forbidden[1].split(',').map((s) => s.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean)
      : [],
  };
};

/** The one-line doc-comment at the top of each script, so the file map says what each file is for. */
const fileMap = () => {
  const dir = path.join(ROOT, 'scripts');
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.mjs'))
    .sort()
    .map((f) => {
      const src = fs.readFileSync(path.join(dir, f), 'utf8');
      const m = src.match(/^\/\*\*\s*\n\s*\*\s*(.+)$/m);
      return { file: `scripts/${f}`, purpose: m ? m[1].trim() : '—', bytes: fs.statSync(path.join(dir, f)).size };
    });
};

export const explainAll = (org, { help = '' } = {}) => {
  const L = [];
  const c = org.constitution;

  L.push('# F.O.R.G.E. — System Reference');
  L.push('');
  L.push('**Generated by `forge explain --all`. Do not hand-edit — regenerate.**');
  L.push('');
  L.push('Every section below is composed from the same source `forge doctor` audits, so this');
  L.push('document cannot describe an organization different from the one that runs. If something');
  L.push('here is wrong, the registry is wrong.');
  L.push('');
  L.push(`${org.all.length} agents · ${c.divisions.length} divisions · ${org.roster.board.length} board seats · ${c.rules.length} rules · ${c.gates.length} gates`);
  L.push('');
  L.push('---');
  L.push('');

  // ---- rules
  L.push(H(2, 'The rules, and the check that enforces each'));
  L.push('');
  L.push('`core.load()` refuses to start if a rule names a check no code implements, so this table');
  L.push('cannot contain a rule that is enforced by nothing.');
  L.push('');
  L.push('| Rule | Title | Enforcing check |');
  L.push('|---|---|---|');
  for (const r of c.rules) L.push(`| ${r.id} | ${r.title} | \`${r.check}\` |`);
  L.push('');

  // ---- principles
  L.push(H(2, 'The principles, and which are aspirational'));
  L.push('');
  L.push('| Principle | Enforcement |');
  L.push('|---|---|');
  for (const p of c.board.principles || []) {
    const e = p.enforcement || 'undeclared';
    L.push(`| ${p.name} | ${e === 'aspirational' ? '_aspirational_' : `\`${e}\``} |`);
  }
  L.push('');

  // ---- gates
  L.push(H(2, 'The gates'));
  L.push('');
  for (const g of c.gates) {
    L.push(`- **${g.title}** — ${g.why}`);
    L.push(`  - fires on: ${(g.matches || []).map((m) => `\`${m}\``).join(', ')}`);
  }
  L.push('');

  // ---- circuit breakers
  L.push(H(2, 'Circuit breakers'));
  L.push('');
  L.push('Exceed → STOP → REPORT → ESCALATE. Each has a predicate in `scripts/breakers.mjs`.');
  L.push('');
  L.push('| Breaker | Limit |');
  L.push('|---|---|');
  for (const [k, v] of Object.entries(c.circuit_breakers || {})) L.push(`| \`${k}\` | ${v} |`);
  L.push('');

  // ---- board
  L.push(H(2, 'The board'));
  L.push('');
  L.push('There is no chief executive. The Chair convenes, sequences and records, and breaks no tie.');
  L.push('');
  L.push('| Seat | Owns | Tier |');
  L.push('|---|---|---|');
  for (const pf of c.board.portfolios) {
    const seat = org.roster.board.find((b) => b.id === pf.seat);
    L.push(`| ${seat ? seat.seat : pf.seat} | ${pf.owns.join(', ')} | \`${seat ? seat.model : '?'}\` |`);
  }
  L.push('');

  // ---- divisions and agents
  L.push(H(2, 'Every division, every agent'));
  L.push('');
  for (const d of c.divisions) {
    const members = org.byDivision.get(d.id) || [];
    L.push(H(3, `${d.name} (${d.id})`));
    L.push('');
    if (d.authority) L.push(`> ${d.authority}`);
    L.push('');
    L.push('| Agent | Role | Tier | Writes | Capabilities | Owns |');
    L.push('|---|---|---|---|---|---|');
    for (const a of members) {
      L.push(`| \`${a.name}\` | ${a.role} | ${a.model} | ${a.writes ? 'yes' : 'no'} | ${(a.capabilities || []).join(', ') || '—'} | ${a.owns} |`);
    }
    L.push('');
  }

  // ---- routing
  L.push(H(2, 'Routing — which request phrasing reaches which capability, and who holds it'));
  L.push('');
  const holders = new Map();
  for (const a of org.all) {
    for (const cap of a.capabilities || []) {
      if (!holders.has(cap)) holders.set(cap, []);
      holders.get(cap).push(a.name);
    }
  }
  L.push('| Rule | Fires on | Capabilities | Held by | Phase |');
  L.push('|---|---|---|---|---|');
  for (const r of org.routing.rules) {
    const trig = r.always ? '_always_' : (r.when_any || []).map((w) => `\`${w}\``).join(', ');
    const held = (r.capabilities || []).flatMap((cap) => holders.get(cap) || []);
    L.push(`| ${r.id} | ${trig} | ${(r.capabilities || []).join(', ')} | ${[...new Set(held)].join(', ') || '**nobody**'} | ${r.phase || '—'} |`);
  }
  L.push('');

  // ---- contracts
  L.push(H(2, 'Output contracts — what each agent must state'));
  L.push('');
  L.push('Composed, never authored per agent: `base` + the agent\'s role + every capability family it joins.');
  L.push('');
  L.push(`**base** (every agent, always): ${org.contracts.base.fields.map((f) => `\`${f.key}\``).join(', ')}`);
  L.push('');
  L.push(`**when applicable**: ${(org.contracts.base.when_applicable || []).map((f) => `\`${f.key}\``).join(', ')}`);
  L.push('');
  for (const [role, spec] of Object.entries(org.contracts.by_role || {})) {
    L.push(`**by role — ${role}**: ${(spec.fields || []).map((f) => `\`${f.key}\``).join(', ') || '—'}`);
  }
  L.push('');
  for (const fam of org.contracts.by_family || []) {
    L.push(`**family ${fam.name}** (${fam.capabilities.join(', ')}): ${(fam.fields || []).map((f) => `\`${f.key}\``).join(', ') || '—'}`);
  }
  L.push('');
  L.push('Resolved size per agent — this is the token cost of the contract, per dispatch:');
  L.push('');
  L.push('| Agent | Required | Optional | Families |');
  L.push('|---|---|---|---|');
  const resolved = org.all
    .map((a) => ({ a, r: resolveContract(a, org.contracts) }))
    .sort((x, y) => y.r.fields.length - x.r.fields.length);
  for (const { a, r } of resolved.slice(0, 10)) {
    L.push(`| \`${a.name}\` | ${r.fields.length} | ${r.optional.length} | ${r.families.join(', ') || '—'} |`);
  }
  L.push('');
  L.push(`_(heaviest 10 of ${org.all.length}; the ceiling is enforced by \`contract_field_count_bounded\`)_`);
  L.push('');

  // ---- CLI
  L.push(H(2, 'The command surface'));
  L.push('');
  L.push('```');
  L.push(String(help).trim());
  L.push('```');
  L.push('');

  // ---- learning limits, printed from the code
  const lim = learningLimits();
  L.push(H(2, 'What the organization may learn, and what it may never touch'));
  L.push('');
  L.push('These are read out of `scripts/learn.mjs` at render time, not transcribed — a doc that');
  L.push('claims a different cap from the one the code enforces is impossible here.');
  L.push('');
  L.push(`**Caps per run:** \`${lim.cap}\``);
  L.push('');
  L.push('**Paths the evolution layer may never write** (plus anything absolute, and anything containing `..`):');
  L.push('');
  for (const f of lim.forbidden) L.push(`- \`${f}\``);
  L.push('');
  L.push('Nothing is applied without the Principal approving it explicitly via `forge evolve --apply <id>`.');
  L.push('');

  // ---- file map
  L.push(H(2, 'File map'));
  L.push('');
  L.push('| File | Purpose | Bytes |');
  L.push('|---|---|---|');
  for (const f of fileMap()) L.push(`| \`${f.file}\` | ${f.purpose} | ${f.bytes} |`);
  L.push('');
  L.push('---');
  L.push('');
  L.push('_Regenerate with `forge explain --all > docs/SYSTEM-REFERENCE.md`._');
  L.push('');
  return L.join('\n');
};

/** One agent's fully resolved prompt — `forge explain <name>`. */
export const explainAgent = (org, name) => {
  const agent = org.byName.get(name);
  if (!agent) {
    const near = org.all.map((a) => a.name).filter((n) => n.includes(name) || name.includes(n));
    throw new Error(`no agent named "${name}"${near.length ? `. Did you mean: ${near.join(', ')}` : ''}`);
  }
  const p = path.join(paths.agents, `${agent.name}.md`);
  if (!fs.existsSync(p)) throw new Error(`${agent.name} is on the roster but not built — run \`forge build --apply\``);
  return fs.readFileSync(p, 'utf8');
};
