/**
 * Install into the host runtime's configuration directory.
 *
 * TWO PROPERTIES THAT ARE NOT NEGOTIABLE
 *
 * 1. It refuses to install an unconstitutional organization. `doctor` runs first and a
 *    failure aborts, because the one machine where a violation matters most is the machine
 *    somebody is about to use.
 *
 * 2. It never clobbers a file it did not write. Anything already present that F.O.R.G.E.
 *    did not generate is reported and skipped, not overwritten. `--force` overwrites, and
 *    says exactly what it replaced.
 *
 * There is no uninstall step that deletes by pattern. Removing agents by wildcard from a
 * directory the Principal also uses by hand is how somebody loses work.
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { paths, ui } from './core.mjs';
import { runDoctor } from './doctor.mjs';
import { build } from './render.mjs';

const MARKER = '<!-- generated by F.O.R.G.E. — edit registry/, not this file -->';

export const home = () => path.join(os.homedir(), '.claude');

export const install = (org, { apply = false, force = false, root = home() } = {}) => {
  const L = [ui.head('FORGE INSTALL')];

  const health = runDoctor(org);
  if (!health.ok) {
    return {
      ok: false,
      report: [...L, '', '  refusing to install an unconstitutional organization.', '', ...health.lines].join('\n'),
    };
  }
  L.push(`\n  constitutional audit: HEALTHY (${health.warnings} warning(s))`);

  // Build fresh into the repo first, so what is installed is what the registry says.
  build(org, { apply: true });

  const agentDir = path.join(root, 'agents');
  const skillDir = path.join(root, 'skills', 'forge');
  const plan = [];

  for (const a of org.all) {
    plan.push({ from: path.join(paths.agents, `${a.name}.md`), to: path.join(agentDir, `${a.name}.md`) });
  }
  plan.push({ from: path.join(paths.skill, 'SKILL.md'), to: path.join(skillDir, 'SKILL.md') });

  let write = 0;
  let skip = 0;
  let replace = 0;
  const conflicts = [];
  for (const p of plan) {
    if (!fs.existsSync(p.to)) {
      write += 1;
      continue;
    }
    const existing = fs.readFileSync(p.to, 'utf8');
    if (existing.includes(MARKER)) {
      replace += 1;
    } else if (force) {
      replace += 1;
      conflicts.push(p.to);
    } else {
      skip += 1;
      conflicts.push(p.to);
    }
  }

  L.push(`  target       ${root}`);
  L.push(`  new          ${write}`);
  L.push(`  ours, update ${replace}`);
  if (skip) {
    L.push(`  NOT ours     ${skip} — skipped. These were not generated by F.O.R.G.E.:`);
    for (const c of conflicts.slice(0, 10)) L.push(`                 ${path.relative(root, c)}`);
    L.push('               run with --force to replace them.');
  }

  if (!apply) {
    L.push('\n  dry run. Nothing written. Add --apply.\n');
    return { ok: true, report: L.join('\n'), applied: false };
  }

  fs.mkdirSync(agentDir, { recursive: true });
  fs.mkdirSync(skillDir, { recursive: true });
  let done = 0;
  for (const p of plan) {
    const exists = fs.existsSync(p.to);
    if (exists && !force && !fs.readFileSync(p.to, 'utf8').includes(MARKER)) continue;
    const body = fs.readFileSync(p.from, 'utf8');
    fs.writeFileSync(p.to, `${body}\n${MARKER}\n`);
    done += 1;
  }
  L.push(`\n  installed ${done} file(s).`);
  L.push('  Set FORGE_HOME so the skill can find the CLI:');
  L.push(`      export FORGE_HOME="${path.resolve(paths.agents, '..')}"\n`);
  return { ok: true, report: L.join('\n'), applied: true };
};

export { MARKER };
