/**
 * Install into the host runtime's configuration directory.
 *
 * TWO PROPERTIES THAT ARE NOT NEGOTIABLE
 *
 * 1. It refuses to install an unconstitutional organization. `doctor` runs first and a
 *    failure aborts, because the one machine where a violation matters most is the machine
 *    somebody is about to use.
 *
 * 2. It never clobbers a file it did not write. Anything already present that F.O.R.G.E.
 *    did not generate is reported and skipped, not overwritten. `--force` overwrites, and
 *    says exactly what it replaced.
 *
 * There is no uninstall step that deletes by pattern. Removing agents by wildcard from a
 * directory the Principal also uses by hand is how somebody loses work.
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { paths, ui, ROOT } from './core.mjs';
import { runDoctor } from './doctor.mjs';
import { build } from './render.mjs';

const MARKER = '<!-- generated by F.O.R.G.E. — edit registry/, not this file -->';

/**
 * The full governance text that used to be injected on every turn.
 *
 * It lives here rather than in the hook because it is only relevant once routing has decided
 * a request is non-trivial — `forge plan --with-policy` prints it at exactly that moment.
 * Exported so the hook and the planner cannot drift into stating different rules, which is
 * the failure that made the previous arrangement a maintenance problem as well as a cost one.
 */
export const POLICY = [
  'GOVERNANCE (F.O.R.G.E.) — this request was routed, so the rules below are in force.',
  '',
  'There is no chief executive. Six board seats own the twelve divisions between them, and a',
  'deadlock escalates to the Principal rather than being broken by a chair.',
  '',
  'SEVEN GATES stop and wait for the Principal: irreversible or destructive action, production',
  'release, schema or data migration, credentials and access, charter amendment, budget',
  'threshold, anything leaving the machine.',
  '',
  'A change that writes must verify — evidence of the matching kind, never a claim of done.',
  'Every claim carries EVIDENCE, INFERENCE or UNKNOWN; an ungraded claim reads as fabricated,',
  'and an EVIDENCE claim inherited from another agent and not re-checked is downgraded to',
  'INFERENCE before it justifies an action.',
  '',
  'A multi-item request decomposes into a checklist before work starts, and completion may not',
  'be reported while any item lacks a terminal status (RULE 014).',
  '',
  'CLOSE THE LEDGER when the campaign ends — one row per specialist, with a token estimate.',
  'A campaign that reports nothing never happened, and routing, Spending and Recognition all',
  'starve without it. Record the grade and the artifacts too (--grade, --artifacts), or the',
  'claim cannot be spot-checked later and RULE 013 has nothing to work with.',
].join('\n');

export const home = () => path.join(os.homedir(), '.claude');

export const install = (org, { apply = false, force = false, root = home() } = {}) => {
  const L = [ui.head('FORGE INSTALL')];

  const health = runDoctor(org);
  if (!health.ok) {
    return {
      ok: false,
      report: [...L, '', '  refusing to install an unconstitutional organization.', '', ...health.lines].join('\n'),
    };
  }
  L.push(`\n  constitutional audit: HEALTHY (${health.warnings} warning(s))`);

  // Build fresh into the repo first, so what is installed is what the registry says.
  build(org, { apply: true });

  const agentDir = path.join(root, 'agents');
  const skillDir = path.join(root, 'skills', 'forge');
  const plan = [];

  for (const a of org.all) {
    plan.push({ from: path.join(paths.agents, `${a.name}.md`), to: path.join(agentDir, `${a.name}.md`) });
  }
  plan.push({ from: path.join(paths.skill, 'SKILL.md'), to: path.join(skillDir, 'SKILL.md') });

  let write = 0;
  let skip = 0;
  let replace = 0;
  const conflicts = [];
  for (const p of plan) {
    if (!fs.existsSync(p.to)) {
      write += 1;
      continue;
    }
    const existing = fs.readFileSync(p.to, 'utf8');
    if (existing.includes(MARKER)) {
      replace += 1;
    } else if (force) {
      replace += 1;
      conflicts.push(p.to);
    } else {
      skip += 1;
      conflicts.push(p.to);
    }
  }

  L.push(`  target       ${root}`);
  L.push(`  new          ${write}`);
  L.push(`  ours, update ${replace}`);
  if (skip) {
    L.push(`  NOT ours     ${skip} — skipped. These were not generated by F.O.R.G.E.:`);
    for (const c of conflicts.slice(0, 10)) L.push(`                 ${path.relative(root, c)}`);
    L.push('               run with --force to replace them.');
  }

  if (!apply) {
    L.push('\n  dry run. Nothing written. Add --apply.\n');
    return { ok: true, report: L.join('\n'), applied: false };
  }

  fs.mkdirSync(agentDir, { recursive: true });
  fs.mkdirSync(skillDir, { recursive: true });
  let done = 0;
  for (const p of plan) {
    const exists = fs.existsSync(p.to);
    if (exists && !force && !fs.readFileSync(p.to, 'utf8').includes(MARKER)) continue;
    const body = fs.readFileSync(p.from, 'utf8');
    fs.writeFileSync(p.to, `${body}\n${MARKER}\n`);
    done += 1;
  }
  L.push(`\n  installed ${done} file(s).`);
  L.push('  Set FORGE_HOME so the skill can find the CLI:');
  L.push(`      export FORGE_HOME="${path.resolve(paths.agents, '..')}"\n`);
  return { ok: true, report: L.join('\n'), applied: true };
};

/**
 * Install or refresh the two hooks in ~/.claude/settings.json.
 *
 * Merge, never replace; write beside and rename, because a half-written settings.json
 * silently disables every setting in the file; parse back before the rename so invalid
 * output never lands; idempotent, so refreshing after an upgrade is the same command.
 * The full payloads and the reasoning live in docs/HOOKS.md.
 */
export const installHooks = ({ root = home(), forgeHome = ROOT } = {}) => {
  // The path baked into env.FORGE_HOME outlives this call by months. A test once ran this
  // from a temporary clone with root accidentally defaulted, and the Principal's live
  // hooks pointed at a directory that was deleted minutes later — the session briefing
  // went silently empty. So: the home this writes must actually be an organization, and
  // a disposable location is refused rather than trusted.
  const resolved = path.resolve(forgeHome);
  if (!fs.existsSync(path.join(resolved, 'scripts', 'forge.mjs'))) {
    throw new Error(`refusing: ${resolved} does not contain scripts/forge.mjs`);
  }
  const tmpRoot = path.resolve(os.tmpdir());
  if (resolved === tmpRoot || resolved.startsWith(tmpRoot + path.sep) || /^(\/private)?\/tmp\//.test(resolved) || resolved.includes('/var/folders/')) {
    throw new Error(`refusing: ${resolved} is a temporary directory — hooks would outlive it`);
  }
  const file = path.join(root, 'settings.json');
  const settings = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  const before = Object.keys(settings).length;

  /**
   * THE HOOK IS PAID ON EVERY TURN, SO IT IS THE SHORT ONE.
   *
   * The previous gate was 186 words injected before every single prompt — a typo fix, a
   * "what does this do", a yes/no. That is a fixed tax on the cheapest interactions, and the
   * expensive ones (the campaigns) were the only ones that needed the governance detail.
   *
   * The content did not go away; it moved to where it is relevant. `forge plan --with-policy`
   * prints the full text at the moment routing has decided the request is non-trivial, so the
   * same words reach the model at the same decision point, paid once per campaign instead of
   * once per turn.
   *
   * The order of the two sentences matters and is not stylistic. The triage question comes
   * FIRST so the model can stop reading; a gate that states its policy before its exit
   * condition has already been paid in full by the time the exit is reached.
   */
  const GATE = [
    'F.O.R.G.E. If this is a lookup, a direct question or a single-line edit, answer it directly —',
    'convening the organization for a typo costs more than the typo.',
    'Otherwise run: node "$FORGE_HOME/scripts/forge.mjs" plan "<request>" --with-policy',
    'before any other tool call, and state the one-line Routing declaration.',
    'If the request carries more than one item, decompose it first —',
    'forge checklist <campaign> --from "<request>" — and do not report done until',
    'forge checklist <campaign> --strict passes (RULE 014).',
    'Close the ledger when it ends: forge observe --agent <n> --capability <c> --outcome ok|partial|fail|blocked.',
  ].join(' ');


  const hooks = { ...(settings.hooks || {}) };
  hooks.UserPromptSubmit = [
    { hooks: [{ type: 'command', command: `echo ${JSON.stringify(JSON.stringify({ hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: GATE }, suppressOutput: true }))}`, timeout: 5 }] },
  ];
  hooks.SessionStart = [
    { hooks: [{ type: 'command', command: 'node "$FORGE_HOME/scripts/forge.mjs" context 2>/dev/null | jq -Rs \'if . == "" then empty else {hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:.},suppressOutput:true} end\' 2>/dev/null || true', timeout: 10, statusMessage: 'Reading what this workspace has taught F.O.R.G.E....' }] },
  ];
  settings.hooks = hooks;
  settings.env = { ...(settings.env || {}), FORGE_HOME: forgeHome };

  const tmp = `${file}.tmp`;
  fs.mkdirSync(root, { recursive: true });
  fs.writeFileSync(tmp, `${JSON.stringify(settings, null, 2)}\n`);
  JSON.parse(fs.readFileSync(tmp, 'utf8'));
  fs.renameSync(tmp, file);
  return { file, keysBefore: before, keysAfter: Object.keys(settings).length };
};

export { MARKER };
